#!/usr/bin/env python3
"""
Parse _themes/theme_*.md → js/themes_data.js

Each theme file has a curated table with three connection levels:
  essential  — 3–5 most important works for the AP exam
  top-pick   — 7–14 highly representative works
  related    — 11–21 contextual works

Outputs THEMES_DATA with essential, top_picks, related, artworks, and
per-artwork thematic connection text (connections dict).
"""

import re
import json
from pathlib import Path


def main():
    themes_dir = Path(__file__).parent.parent / '_themes'
    out_path   = Path(__file__).parent.parent / 'js' / 'themes_data.js'

    md_files = sorted(themes_dir.glob('theme_*.md'))
    print(f"Parsing {len(md_files)} theme files…\n")

    ROW = re.compile(
        r'^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*(essential|top-pick|related)\s*\|\s*(.+?)\s*\|?\s*$'
    )

    out = {}

    for f in md_files:
        key  = f.stem[len('theme_'):]   # e.g. "power_authority"
        text = f.read_text(encoding='utf-8')

        # Label from h1: "# AP Art History — Theme: Power & Authority"
        title_m = re.search(
            r'^#\s+AP Art History\s+[—–-]+\s+Theme:\s+(.+)', text, re.MULTILINE
        )
        label = title_m.group(1).strip() if title_m else key.replace('_', ' ').title()

        # Definition from bold line: "**AP Definition:** ..."
        def_m = re.search(r'^\*\*AP Definition:\*\*\s*(.+)', text, re.MULTILINE)
        definition = def_m.group(1).strip() if def_m else ''

        essential   = []
        top_picks   = []
        related     = []
        connections = {}

        for line in text.splitlines():
            m = ROW.match(line)
            if not m:
                continue
            art_id   = int(m.group(1))
            level    = m.group(3)
            conn_txt = m.group(4).strip()

            connections[art_id] = conn_txt

            if level == 'essential':
                essential.append(art_id)
            elif level == 'top-pick':
                top_picks.append(art_id)
            else:
                related.append(art_id)

        artworks = sorted(set(essential + top_picks + related))

        out[key] = {
            'label':       label,
            'definition':  definition,
            'essential':   essential,
            'top_picks':   top_picks,
            'related':     related,
            'artworks':    artworks,
            'connections': connections,
        }

        print(f"  {key:35s}  {len(essential):2d} essential "
              f"| {len(top_picks):2d} top-picks "
              f"| {len(related):2d} related "
              f"| {len(artworks):3d} total")

    # Write JS file
    js_lines = [
        '// Auto-generated by scripts/build_themes.py — do not edit by hand.',
        '// Primary source: _themes/theme_*.md',
        '// Artwork details (title, artist, dates, image_url, etc.) live in ART_DATA (data.js).',
        '',
        'const THEMES_DATA = ' + json.dumps(out, indent=2) + ';',
        '',
    ]
    out_path.write_text('\n'.join(js_lines), encoding='utf-8')
    print(f"\nWrote {out_path}")


if __name__ == '__main__':
    main()
